name: Auto Merge PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          merge-method: squash