name: Auto Merge PR

on:
  check_suite:
    types: [completed]

jobs:
  automerge:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          merge-method: squash